services:
  - type: web
    name: sparkle-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 zmlb/backend/api.py
    autoDeploy: true

  - type: web
    name: sparkle-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run zmlb/sparkle-health-chatbot/streamlit_chatbot.py --server.port=10000 --server.address=0.0.0.0
    autoDeploy: true
